//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortalWeb.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CVEducation
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public int EducationalDegreeId { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string MajorId { get; set; }
        public string Institute { get; set; }
        public string GPA { get; set; }
    
        public virtual Degree Degree { get; set; }
        public virtual Profile Profile { get; set; }
    }
}
