'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CVEducation
    Public Property Id As Integer
    Public Property UserProfileId As Integer
    Public Property EducationalDegreeId As Integer
    Public Property StartDate As Date
    Public Property EndDate As Nullable(Of Date)
    Public Property MajorId As String
    Public Property Institute As String
    Public Property GPA As String

    Public Overridable Property Degree As Degree
    Public Overridable Property Profile As Profile

End Class
