'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class CvJob
    Public Property Id As Integer
    Public Property UserProfileId As Integer
    Public Property JobTitle As String
    Public Property JobDescription As String
    Public Property StartDate As Date
    Public Property EndDate As Nullable(Of Date)
    Public Property jobResponsibilities As String

    Public Overridable Property Profile As Profile

End Class
