'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Degree
    Public Property Id As Integer
    Public Property Value As String

    Public Overridable Property CVEducations As ICollection(Of CVEducation) = New HashSet(Of CVEducation)
    Public Overridable Property JobsDefinitions As ICollection(Of JobsDefinition) = New HashSet(Of JobsDefinition)

End Class
