'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class EmailNotification
    Public Property Id As Integer
    Public Property Email As String
    Public Property NotificationMessage As String
    Public Property NotificationDatet As Date

End Class
