'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class JobApplication
    Public Property Id As Integer
    Public Property JobId As Integer
    Public Property ApplicantProfileId As Integer
    Public Property ApplicationDate As Date

    Public Overridable Property JobsDefinition As JobsDefinition
    Public Overridable Property Profile As Profile
    Public Overridable Property ScheduledInterviews As ICollection(Of ScheduledInterview) = New HashSet(Of ScheduledInterview)

End Class
