'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated from a template.
'
'     Manual changes to this file may cause unexpected behavior in your application.
'     Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class Profile
    Public Property Id As Integer
    Public Property FullName As String
    Public Property Birthdate As Date
    Public Property GenderId As Integer
    Public Property NationalityId As Nullable(Of Integer)
    Public Property Email As String
    Public Property UserId As String
    Public Property MobileNumber As String
    Public Property FullAddress As String
    Public Property CoverLetter As String

    Public Overridable Property CVEducations As ICollection(Of CVEducation) = New HashSet(Of CVEducation)
    Public Overridable Property CvJobs As ICollection(Of CvJob) = New HashSet(Of CvJob)
    Public Overridable Property CVSkills As ICollection(Of CVSkill) = New HashSet(Of CVSkill)
    Public Overridable Property Gender As Gender
    Public Overridable Property JobApplications As ICollection(Of JobApplication) = New HashSet(Of JobApplication)
    Public Overridable Property Nationality As Nationality

End Class
