//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class CvJob
    {
        public int Id { get; set; }
        public int UserProfileId { get; set; }
        public string JobTitle { get; set; }
        public string JobDescription { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public string jobResponsibilities { get; set; }
    
        public virtual Profile Profile { get; set; }
    }
}
