//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmailNotification
    {
        public int Id { get; set; }
        public string Email { get; set; }
        public string NotificationMessage { get; set; }
        public System.DateTime NotificationDatet { get; set; }
    }
}
