//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JobPortal.Admin.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class Profile
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Profile()
        {
            this.CVEducations = new HashSet<CVEducation>();
            this.CvJobs = new HashSet<CvJob>();
            this.CVSkills = new HashSet<CVSkill>();
            this.JobApplications = new HashSet<JobApplication>();
        }
    
        public int Id { get; set; }
        public string FullName { get; set; }
        public System.DateTime Birthdate { get; set; }
        public int GenderId { get; set; }
        public Nullable<int> NationalityId { get; set; }
        public string Email { get; set; }
        public string UserId { get; set; }
        public string MobileNumber { get; set; }
        public string FullAddress { get; set; }
        public string CoverLetter { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVEducation> CVEducations { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CvJob> CvJobs { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CVSkill> CVSkills { get; set; }
        public virtual Gender Gender { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<JobApplication> JobApplications { get; set; }
        public virtual Nationality Nationality { get; set; }
    }
}
